services:
  presence-beam:
    build: .
    image: presence-beam
    container_name: presence-beam
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
